### ISSUE TITLE
bug: Overriding global Promise

### ISSUE THREAD

**Issue by balintpeak** [mimmi20/browscap-js#17]
I very much like this library, the parsing function seems superior to the other ones out there.

However, the lib has an unwanted side effect of overriding node's global Promise in the entire application.
This causes issues in other parts of my app, so I cannot use this in its current format.

It would be great, if there was no reliance on the `synchronous-promise` lib and instead the global Promise implementation was used

**Comment by balintpeak** [comment]
@mimmi20 If you change 

```
if (typeof process === 'object' && typeof process.versions === 'object' && process.versions.node) {
    let nodejsOnly = '';
    global.Promise = require(nodejsOnly + 'synchronous-promise').SynchronousPromise;
}
```

to:

```let Promise = Promise

if (typeof process === 'object' && typeof process.versions === 'object' && process.versions.node) {
    let nodejsOnly = '';
    Promise = require(nodejsOnly + 'synchronous-promise').SynchronousPromise;
}
```

in
`browscap-js/src/parser/index.js`
`browscap-js/src/helper/data/index.js`
`browscap-js/src/helper/pattern/index.js`

Then the promise override will be local to the given file, and everything seems to work as expected without globally affecting the rest of the app where this lib is used.

**Comment by balintpeak** [comment]
@mimmi20 any feedback on this?

**Comment by mimmi20** [comment]
I removed this code block.
