### ISSUE TITLE
What's the difference between v1, v2, v3, and v4?

### ISSUE THREAD

**Issue by DimitarNestorov** [mimmi20/browscap-js#20]
![image](https://user-images.githubusercontent.com/8790386/45116355-1b1fa880-b15b-11e8-90fa-812b682b8fae.png)
What's the difference between v1, v2, v3, and v4? Which one should I use?

I would also suggest using tags. For example: `4.0.6000029` should have a `v4` tag. Would make installing much easier: `npm install browscap-js@v4`. Right now it would install v1 since the default is `@latest`. I know you can just do `browscap-js@4` but that would write just `4` in `package.json`.

**Comment by mimmi20** [comment]
@dimitarnestorov 
1. v2 and v4 use a Promise inside (implemented in #9), v1 and v3 do not. 
2. v3 and v4 use the class syntax, v1 and v2 do not. 
3. For v3 and v4 you need nodejs v6, v2 need nodejs v4 and v1 should run with any version of nodejs.

Please use v3 or v4. There should no difference in speed.

> I would also suggest using tags

How do I do that?

**Comment by DimitarNestorov** [comment]
Thanks for the explanation! Also I want to congratulate you on the extensive support of various Node versions.

```sh
npm dist-tag add browscap-js@4.0.6000029 v4
npm dist-tag add browscap-js@3.0.6000030 v3
npm dist-tag add browscap-js@2.2.6000030 v2
npm dist-tag add browscap-js@1.11.6000030 v1
```

Here are the docs: https://docs.npmjs.com/cli/dist-tag

I'm also noting `v4` doesn't have `6000030` release.

**Comment by mimmi20** [comment]
> I'm also noting v4 doesn't have 6000030 release.

Now existing

**Comment by mimmi20** [comment]
> npm dist-tag add browscap-js@4.0.6000029 v4

If I try that, I get the error: `Tag name must not be a valid SemVer range: v4`

**Comment by DimitarNestorov** [comment]
Agh. Can't think of a better tag atm. This should work. 
```sh
npm dist-tag add browscap-js@4.0.6000030 version4
npm dist-tag add browscap-js@3.0.6000030 version3
npm dist-tag add browscap-js@2.2.6000030 version2
npm dist-tag add browscap-js@1.11.6000030 version1
```
