### ISSUE TITLE
updating browscap cache

### ISSUE THREAD

**Issue by pmidge** [mimmi20/browscap-js#3]
Hi @mimmi20, I've looked around at the various browscap repos and am not sure how I'd generate a new version of the browscap JSON cache. I want to sync the versions used by our Node & PHP components. Node appears to be using 6014 and PHP is currently on 6015. Thanks!

**Comment by mimmi20** [comment]
The cache files are in the repo `https://github.com/mimmi20/browscap-json-cache-files`. I updated this repo today.

I updated `browscap.js` also with new tests. Please update your installation.

**Comment by pmidge** [comment]
Updated, thank you!
